# Generated by Django 5.0.6 on 2024-05-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fecha_de_partido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
